<?php

namespace AiosInitialSetup\App\Controllers;

class PageNotFoundController
{
  /**
   * PageNotFoundController constructor.
   */
  public function __construct()
  {
    $this->save_error_options($_POST);
    $this->add_actions();
  }

  /**
   * Save Front End Settings
   *
   * @param $post_date
   * @since 2.8.5
   *
   * @access public
   */
  public function save_error_options($post_date)
  {
    $placeholder_val = [
      "photo_left" => AIOS_INITIAL_SETUP_RESOURCES .'images/404-text-image.png' ,
      "photo_right" => AIOS_INITIAL_SETUP_RESOURCES .'images/404-image-right.png',
      "error_verbiage" => "Please check the webpage URL to make sure you have the correct address. It may also be possible that the content of this page is not yet ready for viewing. Feel free to revisit this page at another time or contact the website administrator for further assistance.",
      "error_form" => "[contact-form-7 title='404 Page Form (Auto-generated by AIOS Initial Setup)' html_class='use-floating-validation-tip']",
      "error_template" => "sidebar"
    ];

    if (get_option( '404_settings' ) === ''){
      update_option('404_settings', $placeholder_val);
    } else {
      if (isset($_POST['error-form-flag'])) {
        if (! isset($post_date['error_fields_content']) && wp_verify_nonce($_POST['error_fields_content'], 'error_fields_action')) {
          // Do nothing
        } else {
          $error_options = [
            'photo_left' => isset($post_date['error-left-photo']) ? sanitize_text_field($post_date['error-left-photo']) : '',
            'photo_right' => isset($post_date['error-right-photo']) ? sanitize_text_field($post_date['error-right-photo']) : '',
            'error_verbiage' => isset($post_date['error-verbiage']) ? sanitize_text_field($post_date['error-verbiage']) : '',
            'error_form' => isset($post_date['error-form']) ? sanitize_text_field($post_date['error-form'])  : '',
            'error_template' => isset($post_date['error-template']) ? sanitize_text_field($post_date['error-template'])  : ''
          ];

          update_option('404_settings', isset($error_options) ? $error_options : '');
        }
      }
    }
  }


  /**
   * Add Actions.
   *
   * @since 1.0.0
   *
   * @access protected
   */
  protected function add_actions()
  {
    $settings = get_option('404_settings');
    if (empty($settings['disabled_404'])) {
      add_filter('template_include', [$this, 'page_template'], 11);
    }
  }

  /**
   * Call 404 Page
   *
   * @param $template
   * @return string
   * @since 2.8.5
   *
   * @access public
   */
  public function page_template($template)
  {
    return is_404()? AIOS_INITIAL_SETUP_VIEWS . 'initial-setup' . DIRECTORY_SEPARATOR . 'elements' . DIRECTORY_SEPARATOR . '404-page.php' : $template;
  }
}

new PageNotFoundController();
